#database access self approval & no alternate approver 1 day with jira question Database - lau read access
name: "Database"
policy:
  display_name: "Initial Policy"
  description: "Initial Policy"
  duration_in_days: 1
  approval_settings:
    approval_required_for_extension: true
    approval_required: true
    approval_stage:
      approval_timeout_in_days: 14
      approver_justification_required: true
      enable_alternative_approval_in_days: 0
      primary_approver:
        backup: true
        subject_type: "groupMembers"
    requestor_justification_required: true
  assignment_review_settings:
    access_recommendation_enabled: true
    access_review_timeout_behavior: "keepAccess"
    approver_justification_required: true
    duration_in_days: 14
    enabled: true
    review_frequency: "weekly"
    review_type: "Self"
    reviewer:
      backup: true
      subject_type: "groupMembers"
  extension_enabled: true
  question:
    choice:
      actual_value: actual_value
      display_value:
        default_text: "default_text" 
        localized_text:
          content: "Include JIRA link in business justification expiration"
          language_code: language_code
    required: true
    sequence: 1
    text:
      default_text: "default_text"
      localized_text:
        content: "content"
        language_code: "language_code"
  requestor_settings:
    requestor:
      subject_type: "groupMembers"
    requests_accepted: true
    scope_type: "AllExistingDirectoryMemberUsers"
